import { createDefaultStoragePlan, DEFAULT_DATA_ROOT } from '../data/storagePlan'
import type { SetupConfig } from '../store/setupStore'

export function generateEnvFile(config: SetupConfig, selectedServices: string[]): string {
    const profiles = Array.from(new Set(selectedServices)).join(',')
    const storagePlan = config.storagePlan || createDefaultStoragePlan(DEFAULT_DATA_ROOT)
    const planRoot = storagePlan.dataRoot?.path || DEFAULT_DATA_ROOT
    const storageDefaults = createDefaultStoragePlan(planRoot)

    const resolvePath = (key: string, fallback: string) =>
        storagePlan[key]?.path || storageDefaults[key]?.path || fallback

    const dataRoot = resolvePath('dataRoot', DEFAULT_DATA_ROOT)
    const configRoot = resolvePath('configRoot', `${dataRoot}/config`)
    const moviesPath = resolvePath('movies', `${dataRoot}/media/movies`)
    const tvPath = resolvePath('tv', `${dataRoot}/media/tv`)
    const musicPath = resolvePath('music', `${dataRoot}/media/music`)
    const booksPath = resolvePath('books', `${dataRoot}/media/books`)
    const audiobooksPath = resolvePath('audiobooks', `${dataRoot}/media/audiobooks`)
    const photosPath = resolvePath('photos', `${dataRoot}/media/photos`)
    const transcodePath = resolvePath('transcode', `${dataRoot}/transcode`)
    const downloadsPath = resolvePath('downloads', `${dataRoot}/downloads`)

    let serviceVars = ''
    Object.entries(config.serviceConfigs).forEach(([service, vars]) => {
        if (selectedServices.includes(service)) {
            serviceVars += `\n# ${service.toUpperCase()} CONFIGURATION\n`
            Object.entries(vars).forEach(([key, value]) => {
                serviceVars += `${key}=${value}\n`
            })
        }
    })

    return `# .env configuration for mediastack
# Generated by Interactive Setup Wizard

# =============================================================================
# GENERAL SETTINGS
# =============================================================================
TIMEZONE=${config.timezone}
PUID=${config.puid}
PGID=${config.pgid}
DOMAIN=${config.domain}
DOCKER_NETWORK=mediastack
COMPOSE_PROFILES=${profiles}

# =============================================================================
# STORAGE & PATHS
# =============================================================================
DATA_ROOT=${dataRoot}
CONFIG_ROOT=${configRoot}
MOVIES_PATH=${moviesPath}
TV_SHOWS_PATH=${tvPath}
MUSIC_PATH=${musicPath}
BOOKS_PATH=${booksPath}
AUDIOBOOKS_PATH=${audiobooksPath}
PHOTOS_PATH=${photosPath}
TRANSCODE_PATH=${transcodePath}
DOWNLOADS_PATH=${downloadsPath}

# =============================================================================
# SERVICE CREDENTIALS & SECRETS
# =============================================================================
CLOUDFLARE_TUNNEL_TOKEN=${config.cloudflareToken || 'changeme'}
# Cloudflare Tunnel run command. Example:
# - tunnel run --token <CLOUDFLARE_TUNNEL_TOKEN>
CLOUDFLARED_COMMAND=

# Authelia Secrets (Generate strictly random strings for production)
AUTHELIA_IDENTITY_VALIDATION_RESET_PASSWORD_JWT_SECRET=changeme_random_string
AUTHELIA_SESSION_SECRET=changeme_random_string
AUTHELIA_STORAGE_ENCRYPTION_KEY=changeme_random_string

# Passwords
REDIS_PASSWORD=${config.password}
PHOTOPRISM_ADMIN_PASSWORD=changeme

# API Keys (Fill these in after setting up services)
PLEX_TOKEN=
JELLYFIN_API_KEY=
SONARR_API_KEY=
RADARR_API_KEY=
PROWLARR_API_KEY=
BAZARR_API_KEY=
OVERSEERR_API_KEY=
TAUTULLI_API_KEY=
PORTAINER_TOKEN=

# Plex Claim Token (https://www.plex.tv/claim)
PLEX_CLAIM=${config.plexClaim || ''}

# Gluetun VPN (WireGuard)
WIREGUARD_PRIVATE_KEY=${config.wireguardPrivateKey || ''}
WIREGUARD_ADDRESSES=${config.wireguardAddresses || ''}
WIREGUARD_PRESHARED_KEY=
WIREGUARD_PUBLIC_KEY=
WIREGUARD_ENDPOINT_IP=
WIREGUARD_ENDPOINT_PORT=

# =============================================================================
# SERVICE SPECIFIC CONFIGURATION
# =============================================================================
${serviceVars}
`
}

