#!/bin/bash

# Auto-Build Environment Setup for Media Stack Investigation
# Generated by Planner Agent

set -e

echo "========================================"
echo "Media Stack Development Environment"
echo "========================================"

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m'

# Project root (escaped for spaces in path)
PROJECT_ROOT="/Users/morlock/fun/m2 copy 2/Media-stack-anti"

cd "$PROJECT_ROOT"

# Wait for service function
wait_for_service() {
    local port=$1
    local name=$2
    local max=60
    local count=0

    echo "Waiting for $name on port $port..."
    while ! nc -z localhost $port 2>/dev/null; do
        count=$((count + 1))
        if [ $count -ge $max ]; then
            echo -e "${RED}$name failed to start after ${max}s${NC}"
            return 1
        fi
        sleep 1
    done
    echo -e "${GREEN}$name ready on port $port${NC}"
}

# ============================================
# VERIFY DEPENDENCIES
# ============================================

echo ""
echo "Checking dependencies..."

if ! command -v node &> /dev/null; then
    echo -e "${RED}Node.js is not installed${NC}"
    exit 1
fi

if ! command -v npm &> /dev/null; then
    echo -e "${RED}npm is not installed${NC}"
    exit 1
fi

NODE_VERSION=$(node -v)
echo -e "${GREEN}Node.js: $NODE_VERSION${NC}"

# Check if node_modules exists
if [ ! -d "node_modules" ]; then
    echo -e "${YELLOW}Installing dependencies...${NC}"
    npm install
fi

# ============================================
# BUILD CHECK (Optional but recommended)
# ============================================

echo ""
echo "Running build verification..."
if npm run build; then
    echo -e "${GREEN}Build successful${NC}"
else
    echo -e "${RED}Build failed - check for TypeScript errors${NC}"
    exit 1
fi

# ============================================
# START SERVICES
# ============================================

echo ""
echo "Starting development servers..."

# Start control-server (port 3001)
echo "Starting control-server..."
npm run dev -w control-server &
CONTROL_PID=$!
wait_for_service 3001 "Control Server"

# Start docs-site (port 5173)
echo "Starting docs-site..."
npm run dev -w docs-site &
DOCS_PID=$!
wait_for_service 5173 "Docs Site"

# ============================================
# SUMMARY
# ============================================

echo ""
echo "========================================"
echo -e "${GREEN}Environment Ready!${NC}"
echo "========================================"
echo ""
echo "Services:"
echo "  Control Server:  http://localhost:3001"
echo "  Docs Site:       http://localhost:5173"
echo ""
echo "API Endpoints:"
echo "  Health:          http://localhost:3001/api/health"
echo "  Containers:      http://localhost:3001/api/containers"
echo "  Settings:        http://localhost:3001/api/settings/openai-key"
echo ""
echo "Test Commands:"
echo "  npm run check              # Quick validation (lint + tests)"
echo "  npm test -w control-server # Run Vitest unit tests"
echo "  npm test -w docs-site      # Run Playwright E2E tests"
echo ""
echo "Press Ctrl+C to stop all services"

# Trap to cleanup on exit
cleanup() {
    echo ""
    echo "Shutting down services..."
    kill $CONTROL_PID 2>/dev/null || true
    kill $DOCS_PID 2>/dev/null || true
    echo "Done"
}

trap cleanup EXIT INT TERM

# Wait for either process to exit
wait
