steps:
  # Prepare context
  - name: 'ubuntu'
    args: ['cp', 'docker-compose.yml', 'control-server/']
    id: 'prepare-context'

  # Build Control Server
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/control-server:latest', './control-server']
    id: 'build-control-server'
    waitFor: ['prepare-context']

  # Build Docs Site
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/docs-site:latest', './docs-site']
    id: 'build-docs-site'
    waitFor: ['-'] # Run in parallel

  # Push Control Server
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/control-server:latest']
    id: 'push-control-server'
    waitFor: ['build-control-server']

  # Push Docs Site
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/docs-site:latest']
    id: 'push-docs-site'
    waitFor: ['build-docs-site']

  # Deploy Control Server to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'media-stack-control'
      - '--image'
      - 'gcr.io/$PROJECT_ID/control-server:latest'
      - '--region'
      - 'us-central1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
    waitFor: ['push-control-server']
    
  # Deploy Docs Site to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'media-stack-docs'
      - '--image'
      - 'gcr.io/$PROJECT_ID/docs-site:latest'
      - '--region'
      - 'us-central1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
    waitFor: ['push-docs-site']

images:
  - 'gcr.io/$PROJECT_ID/control-server:latest'
  - 'gcr.io/$PROJECT_ID/docs-site:latest'
