import { useState } from 'react'
import { motion } from 'framer-motion'
import {
    Tv, Film, Download, Shield, Activity,
    Check, Copy, Terminal, Layers, Cpu, Globe,
    Settings, Clock, User, Lock, FileText, ChevronDown, ChevronUp
} from 'lucide-react'

interface ServiceOption {
    id: string
    name: string
    description: string
    icon: any
    profile: string
    category: 'core' | 'media' | 'automation' | 'download' | 'monitoring'
}

const services: ServiceOption[] = [
    {
        id: 'plex',
        name: 'Plex',
        description: 'Premium media server with polished UI.',
        icon: Film,
        profile: 'plex',
        category: 'media'
    },
    {
        id: 'jellyfin',
        name: 'Jellyfin',
        description: 'Free, open-source media server.',
        icon: Tv,
        profile: 'jellyfin',
        category: 'media'
    },
    {
        id: 'arr',
        name: '*Arr Stack',
        description: 'Sonarr, Radarr, Prowlarr, Bazarr.',
        icon: Layers,
        profile: 'arr',
        category: 'automation'
    },
    {
        id: 'torrent',
        name: 'Torrent Client',
        description: 'qBittorrent routed through VPN.',
        icon: Download,
        profile: 'torrent',
        category: 'download'
    },
    {
        id: 'vpn',
        name: 'Gluetun VPN',
        description: 'Secure tunnel for downloads.',
        icon: Shield,
        profile: 'vpn',
        category: 'download'
    },
    {
        id: 'transcode',
        name: 'Tdarr',
        description: 'Distributed transcoding to save space.',
        icon: Cpu,
        profile: 'transcode',
        category: 'automation'
    },
    {
        id: 'stats',
        name: 'Tautulli',
        description: 'Detailed Plex usage statistics.',
        icon: Activity,
        profile: 'stats',
        category: 'monitoring'
    },
    {
        id: 'notify',
        name: 'Notifiarr',
        description: 'Unified notifications (Discord).',
        icon: Globe,
        profile: 'notify',
        category: 'monitoring'
    }
]

export function StackBuilder() {
    const [selected, setSelected] = useState<string[]>(['plex', 'arr', 'torrent', 'vpn'])
    const [config, setConfig] = useState({
        domain: 'example.com',
        timezone: 'Etc/UTC',
        puid: '1000',
        pgid: '1000',
        password: 'Morlock52$'
    })
    const [copied, setCopied] = useState(false)
    const [showEnv, setShowEnv] = useState(false)

    const toggleService = (id: string) => {
        setSelected(prev =>
            prev.includes(id)
                ? prev.filter(s => s !== id)
                : [...prev, id]
        )
    }

    const handleConfigChange = (key: string, value: string) => {
        setConfig(prev => ({ ...prev, [key]: value }))
    }

    const generateCommand = () => {
        const profiles = selected.join(',')
        return `chmod +x setup_auto.sh && \\
export DOMAIN="${config.domain}" \\
export TIMEZONE="${config.timezone}" \\
export PUID=${config.puid} \\
export PGID=${config.pgid} \\
export MASTER_PASSWORD="${config.password}" \\
export COMPOSE_PROFILES=${profiles} \\
&& ./setup_auto.sh`
    }

    const generateEnvPreview = () => {
        const profiles = selected.join(',')
        return `# .env configuration for mediastack
# Generated by Gemini Builder

# =============================================================================
# GENERAL SETTINGS
# =============================================================================
TIMEZONE=${config.timezone}
PUID=${config.puid}
PGID=${config.pgid}
DOMAIN=${config.domain}
DOCKER_NETWORK=mediastack
COMPOSE_PROFILES=${profiles}

# =============================================================================
# STORAGE & PATHS
# =============================================================================
DATA_ROOT=./data
CONFIG_ROOT=\${DATA_ROOT}/config
MOVIES_PATH=\${DATA_ROOT}/media/movies
TV_SHOWS_PATH=\${DATA_ROOT}/media/tv
MUSIC_PATH=\${DATA_ROOT}/media/music
BOOKS_PATH=\${DATA_ROOT}/media/books
AUDIOBOOKS_PATH=\${DATA_ROOT}/media/audiobooks
PHOTOS_PATH=\${DATA_ROOT}/media/photos
TRANSCODE_PATH=\${DATA_ROOT}/transcode
DOWNLOADS_PATH=\${DATA_ROOT}/downloads

# =============================================================================
# SERVICE CREDENTIALS & SECRETS
# =============================================================================
CLOUDFLARE_TUNNEL_TOKEN=CHANGE_ME_TOKEN

# Authelia Secrets (Generated)
AUTHELIA_JWT_SECRET=$(openssl rand -hex 32)
AUTHELIA_SESSION_SECRET=$(openssl rand -hex 32)
AUTHELIA_STORAGE_ENCRYPTION_KEY=$(openssl rand -hex 32)

# Passwords
REDIS_PASSWORD=${config.password}

# API Keys (Fill these in later)
PLEX_TOKEN=
JELLYFIN_API_KEY=
SONARR_API_KEY=
RADARR_API_KEY=
PROWLARR_API_KEY=
BAZARR_API_KEY=
OVERSEERR_API_KEY=
TAUTULLI_API_KEY=
PORTAINER_TOKEN=

# Plex
PLEX_CLAIM=

# PhotoPrism
PHOTOPRISM_ADMIN_PASSWORD=

# Gluetun VPN
WIREGUARD_PRIVATE_KEY=
WIREGUARD_ADDRESSES=`
    }

    const copyToClipboard = (text: string) => {
        navigator.clipboard.writeText(text)
        setCopied(true)
        setTimeout(() => setCopied(false), 2000)
    }

    return (
        <div className="min-h-screen pt-24 pb-12 px-4 sm:px-6 lg:px-8">
            <div className="max-w-7xl mx-auto">
                <div className="text-center mb-16">
                    <motion.h1
                        initial={{ opacity: 0, y: 20 }}
                        animate={{ opacity: 1, y: 0 }}
                        className="text-4xl md:text-6xl font-bold bg-clip-text text-transparent bg-gradient-to-r from-blue-400 via-purple-400 to-pink-400 mb-6"
                    >
                        Build Your Stack
                    </motion.h1>
                    <motion.p
                        initial={{ opacity: 0, y: 20 }}
                        animate={{ opacity: 1, y: 0 }}
                        transition={{ delay: 0.1 }}
                        className="text-xl text-gray-400 max-w-2xl mx-auto"
                    >
                        Customize your installation. Configure your environment, select services, and generate your setup command.
                    </motion.p>
                </div>

                <div className="grid grid-cols-1 lg:grid-cols-3 gap-8 mb-12">
                    {/* Configuration Panel */}
                    <motion.div
                        initial={{ opacity: 0, x: -20 }}
                        animate={{ opacity: 1, x: 0 }}
                        transition={{ delay: 0.2 }}
                        className="lg:col-span-1 space-y-6"
                    >
                        <div className="glass-panel p-6 rounded-2xl border border-white/10">
                            <div className="flex items-center gap-3 mb-6">
                                <Settings className="w-5 h-5 text-purple-400" />
                                <h2 className="text-xl font-semibold text-white">Configuration</h2>
                            </div>

                            <div className="space-y-4">
                                <div>
                                    <label className="block text-sm font-medium text-gray-400 mb-1">Domain</label>
                                    <div className="relative">
                                        <Globe className="absolute left-3 top-2.5 w-4 h-4 text-gray-500" />
                                        <input
                                            type="text"
                                            value={config.domain}
                                            onChange={(e) => handleConfigChange('domain', e.target.value)}
                                            className="w-full bg-black/30 border border-white/10 rounded-lg py-2 pl-10 pr-4 text-white focus:outline-none focus:border-purple-500 transition-colors"
                                            placeholder="example.com"
                                        />
                                    </div>
                                </div>

                                <div>
                                    <label className="block text-sm font-medium text-gray-400 mb-1">Timezone</label>
                                    <div className="relative">
                                        <Clock className="absolute left-3 top-2.5 w-4 h-4 text-gray-500" />
                                        <input
                                            type="text"
                                            value={config.timezone}
                                            onChange={(e) => handleConfigChange('timezone', e.target.value)}
                                            className="w-full bg-black/30 border border-white/10 rounded-lg py-2 pl-10 pr-4 text-white focus:outline-none focus:border-purple-500 transition-colors"
                                            placeholder="Etc/UTC"
                                        />
                                    </div>
                                </div>

                                <div className="grid grid-cols-2 gap-4">
                                    <div>
                                        <label className="block text-sm font-medium text-gray-400 mb-1">PUID</label>
                                        <div className="relative">
                                            <User className="absolute left-3 top-2.5 w-4 h-4 text-gray-500" />
                                            <input
                                                type="text"
                                                value={config.puid}
                                                onChange={(e) => handleConfigChange('puid', e.target.value)}
                                                className="w-full bg-black/30 border border-white/10 rounded-lg py-2 pl-10 pr-4 text-white focus:outline-none focus:border-purple-500 transition-colors"
                                                placeholder="1000"
                                            />
                                        </div>
                                    </div>
                                    <div>
                                        <label className="block text-sm font-medium text-gray-400 mb-1">PGID</label>
                                        <div className="relative">
                                            <User className="absolute left-3 top-2.5 w-4 h-4 text-gray-500" />
                                            <input
                                                type="text"
                                                value={config.pgid}
                                                onChange={(e) => handleConfigChange('pgid', e.target.value)}
                                                className="w-full bg-black/30 border border-white/10 rounded-lg py-2 pl-10 pr-4 text-white focus:outline-none focus:border-purple-500 transition-colors"
                                                placeholder="1000"
                                            />
                                        </div>
                                    </div>
                                </div>

                                <div>
                                    <label className="block text-sm font-medium text-gray-400 mb-1">Master Password</label>
                                    <div className="relative">
                                        <Lock className="absolute left-3 top-2.5 w-4 h-4 text-gray-500" />
                                        <input
                                            type="password"
                                            value={config.password}
                                            onChange={(e) => handleConfigChange('password', e.target.value)}
                                            className="w-full bg-black/30 border border-white/10 rounded-lg py-2 pl-10 pr-4 text-white focus:outline-none focus:border-purple-500 transition-colors"
                                            placeholder="Use a strong passphrase"
                                        />
                                    </div>
                                </div>
                            </div>
                        </div>
                    </motion.div>

                    {/* Stack Selection */}
                    <div className="lg:col-span-2">
                        <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                            {services.map((service, index) => {
                                const isSelected = selected.includes(service.profile)
                                const Icon = service.icon

                                return (
                                    <motion.div
                                        key={service.id}
                                        initial={{ opacity: 0, scale: 0.9 }}
                                        animate={{ opacity: 1, scale: 1 }}
                                        transition={{ delay: index * 0.05 }}
                                        onClick={() => toggleService(service.profile)}
                                        className={`relative p-4 rounded-xl cursor-pointer border transition-all duration-300 ${isSelected
                                            ? 'bg-purple-500/10 border-purple-500/50 shadow-lg shadow-purple-500/10'
                                            : 'glass-card border-white/5 hover:border-white/10'
                                            }`}
                                    >
                                        <div className="flex items-start justify-between mb-2">
                                            <div className={`p-2 rounded-lg ${isSelected ? 'bg-purple-500/20 text-purple-300' : 'bg-white/5 text-gray-400'
                                                }`}>
                                                <Icon className="w-5 h-5" />
                                            </div>
                                            {isSelected && (
                                                <div className="bg-green-500/20 text-green-400 p-1 rounded-full">
                                                    <Check className="w-3 h-3" />
                                                </div>
                                            )}
                                        </div>
                                        <h3 className={`text-base font-semibold mb-1 ${isSelected ? 'text-white' : 'text-gray-300'}`}>
                                            {service.name}
                                        </h3>
                                        <p className="text-xs text-gray-400">
                                            {service.description}
                                        </p>
                                    </motion.div>
                                )
                            })}
                        </div>
                    </div>
                </div>

                {/* Generated Command Section */}
                <motion.div
                    initial={{ opacity: 0, y: 20 }}
                    animate={{ opacity: 1, y: 0 }}
                    transition={{ delay: 0.4 }}
                    className="glass-panel p-6 rounded-2xl max-w-4xl mx-auto border border-white/10"
                >
                    <div className="flex items-center justify-between mb-4">
                        <div className="flex items-center gap-3">
                            <Terminal className="w-5 h-5 text-purple-400" />
                            <h2 className="text-lg font-semibold text-white">Installation Command</h2>
                        </div>
                        <button
                            onClick={() => setShowEnv(!showEnv)}
                            className="flex items-center gap-2 text-sm text-gray-400 hover:text-white transition-colors"
                        >
                            <FileText className="w-4 h-4" />
                            {showEnv ? 'Hide .env Preview' : 'Show .env Preview'}
                            {showEnv ? <ChevronUp className="w-4 h-4" /> : <ChevronDown className="w-4 h-4" />}
                        </button>
                    </div>

                    <div className="relative group mb-4">
                        <div className="bg-black/50 rounded-xl p-4 font-mono text-sm text-gray-300 break-all border border-white/10 overflow-x-auto">
                            <pre className="whitespace-pre-wrap">{generateCommand()}</pre>
                        </div>
                        <button
                            onClick={() => copyToClipboard(generateCommand())}
                            className="absolute top-2 right-2 p-2 bg-white/10 hover:bg-white/20 rounded-lg transition-colors text-white"
                            title="Copy command"
                        >
                            {copied ? <Check className="w-4 h-4 text-green-400" /> : <Copy className="w-4 h-4" />}
                        </button>
                    </div>

                    {showEnv && (
                        <motion.div
                            initial={{ opacity: 0, height: 0 }}
                            animate={{ opacity: 1, height: 'auto' }}
                            className="mt-4 pt-4 border-t border-white/10"
                        >
                            <div className="flex items-center justify-between mb-2">
                                <span className="text-sm text-gray-400">Generated .env content:</span>
                                <button
                                    onClick={() => copyToClipboard(generateEnvPreview())}
                                    className="text-xs flex items-center gap-1 text-purple-400 hover:text-purple-300"
                                >
                                    <Copy className="w-3 h-3" /> Copy .env
                                </button>
                            </div>
                            <div className="bg-black/50 rounded-xl p-4 font-mono text-xs text-gray-400 border border-white/10 overflow-x-auto max-h-96 overflow-y-auto">
                                <pre>{generateEnvPreview()}</pre>
                            </div>
                        </motion.div>
                    )}

                    <p className="mt-4 text-sm text-gray-500 text-center">
                        Run the command above to configure and start your stack automatically.
                    </p>
                </motion.div>
            </div>
        </div>
    )
}
